PRODUCTS = [
    {
        "key": "rosie",
        "name": "Rosie",
        "family": "Female",
        "price": 180.00,
        "size": "50ml",
        "image": "WhatsApp Image 2026-05-27 at 09.07.42.jpeg",
        "tagline": "Long-lasting, blooming florals",
        "notes": "Peony, rose water, soft musk",
        "occasions": "Date night · Weddings · Evenings",
        "pay_link": "https://pay.yoco.com/r/7KEK5q",
        "featured": True,
        "badge": "Bestseller",
    },
    {
        "key": "sweetapple",
        "name": "Sweetapple",
        "family": "Unisex",
        "price": 180.00,
        "size": "50ml",
        "image": "WhatsApp Image 2026-05-27 at 09.05.30.jpeg",
        "tagline": "Crisp, juicy and long-lasting",
        "notes": "Red apple, fresh green accord, vanilla",
        "occasions": "Day wear · Office · Casual",
        "pay_link": "https://pay.yoco.com/r/mEbKMD",
        "featured": True,
        "badge": "Winter Sale",
    },
    {
        "key": "apple-blaze",
        "name": "Apple Blaze",
        "family": "Unisex",
        "price": 180.00,
        "size": "50ml",
        "image": "apple blaze.jpeg",
        "tagline": "A fiery caramelised apple accord",
        "notes": "Baked apple, warm amber, caramel",
        "occasions": "Cooler days · Evenings · Winter",
        "pay_link": "https://pay.yoco.com/r/mEbKMD",
        "featured": False,
        "badge": "Limited",
    },
    {
        "key": "woody",
        "name": "Woody",
        "family": "Male",
        "price": 180.00,
        "size": "50ml",
        "image": "woody2.png",
        "tagline": "Bold, masculine, grounded",
        "notes": "Cedarwood, sandalwood, smoky vetiver",
        "occasions": "Business · Evenings · All season",
        "pay_link": "https://pay.yoco.com/r/7KEK5q",
        "featured": False,
        "badge": "New",
    },
    {
        "key": "noir-velvet",
        "name": "Noir Velvet",
        "family": "Female",
        "price": 180.00,
        "size": "50ml",
        "image": "IMG-20260429-WA0066.jpg",
        "tagline": "Mysterious and sensual",
        "notes": "Blackberry, dark plum, amber musk",
        "occasions": "Evenings · Gala · Signature",
        "pay_link": "https://pay.yoco.com/r/7KEK5q",
        "featured": False,
        "badge": "Evening",
    },
    {
        "key": "sweetapple-rose",
        "name": "Sweet Apple Rose",
        "family": "Unisex",
        "price": 180.00,
        "size": "50ml",
        "image": "sweetapple.jpeg",
        "tagline": "Rosy apple, fresh and fun",
        "notes": "Ripe apple, rose petals, sugar",
        "occasions": "Day wear · Brunch · Gift",
        "pay_link": "https://pay.yoco.com/r/mEbKMD",
        "featured": False,
        "badge": "Gift Idea",
    },
    {
        "key": "signature-gold",
        "name": "Signature Gold",
        "family": "Unisex",
        "price": 180.00,
        "size": "50ml",
        "image": "WhatsApp Image 2026-05-11 at 14.58.30.jpeg",
        "tagline": "The house signature — timeless luxury",
        "notes": "Golden amber, white florals, oud",
        "occasions": "Any occasion · Signature scent",
        "pay_link": "https://pay.yoco.com/r/7KEK5q",
        "featured": True,
        "badge": "Signature",
    },
]

FAMILIES = ["All", "Female", "Male", "Unisex"]

SOCIAL_LINKS = {
    "TikTok": "https://www.tiktok.com/@sthandiwe386?is_from_webapp=1&sender_device=pc",
    "Instagram": "https://www.instagram.com/luthuliscents?igsh=NzJvNDNxbDJsY3Jv",
    "WhatsApp": "https://wa.me/27692380796",
    "X / Twitter": "https://x.com/L68220Luthuli",
    "Email": "mailto:sthandiweluthuli322@gmail.com",
    "Facebook": "https://www.facebook.com/profile.php?id=61583709642144",
}
